trigger: none
pr:
  branches:
    include:
    - nopip
    exclude:
    - main
    - hotfix/*
    - feature/*

resources:
- repo: self

pool:
   vmImage: 'ubuntu-latest'

steps:
  - script: |
      echo $(ENVIRONMENT)
  - task: GoTool@0
    inputs:
      version: '1.15'
  - task: Go@0
    inputs:
      command: 'get'
  - task: Go@0
    inputs:
      command: 'build'
  - task: Go@0
    inputs:
      command: 'test'
      arguments: '-v ./...'
  
  
