package main

import (
	"fmt"
	"log"
	"net/http"

	"github.com/gorilla/mux"
	"github.com/heyjoakim/devops-21/routers"

	_ "github.com/heyjoakim/devops-21/docs" // docs is generated by Swag CLI, you have to import it.
	httpSwagger "github.com/swaggo/http-swagger"
)

func main() {
	router := mux.NewRouter()

	s := http.StripPrefix("/static/", http.FileServer(http.Dir("./static/")))
	router.PathPrefix("/static/").Handler(s)
	routers.AddUiRouter(router)

	apiRouter := router.PathPrefix("/api").Subrouter()
	routers.AddAPIRoutes(apiRouter)

	// Swagger
	apiRouter.PathPrefix("/swagger").Handler(httpSwagger.WrapHandler)

	PORT := ":8000"
	fmt.Printf("Server is running on http://localhost%s\n", PORT)
	log.Fatal(http.ListenAndServe(PORT, router))
}
